### ISSUE TITLE
UBWireTool error

### ISSUE THREAD

**Issue by vgenty** [LArbys/larlitecv#8]
Another error encountered in running the tagger
`what():  UBWireTool.cxx::425 Wire ID=-2147483648 Plane=2 could not find wireStart or wireEnd`

stdout:
https://gist.github.com/vgenty/ce2056f01dc75fd5719f5b8790642d98

gdb bt:
https://gist.github.com/vgenty/c8e880c8e2122570c1cbf37589ada468

f 6:
https://gist.github.com/vgenty/c87a16734a1c450a84304d63a2697543

the offending event... (2.7M)
https://www.nevis.columbia.edu/~vgenty/public/for_expert_debug_again.tar

**Comment by twongjirad** [comment]
This exception was caused by some upstream component of the tagger setting a boundaryspacepoint outside the image bounds.  it seems to stem from a rounding issue where converting from the y-max row, row=0, to 3d space, then back again causes a shift by -1 row, which is out of image.

I provided a work around that should suffice for now.  the test event passes by checking for spacepoints being outside the image.
